main: me.SuperRonanCraft.BetterRTPAddons.Main
version: 1.4
api-version: '1.13'
name: BetterRTPAddons
depend: [BetterRTP]
softdepend: [ProtocolLib]

permissions:
  betterrtp.addon.portals:
    description: Ability to use the portals addon commands

